#!/home/fkalter/perl

use 5.016000;
use warnings;

use Path::Class;
use IPC::Open3 qw( open3 );
use Carp;

chomp $ARGV[0];
my $file = file($ARGV[0]);
my $dir = $file->dir;
$dir = quotemeta($dir);

open(my $fh, ">>", "/home/fkalter/scripts/extract-iso.log") or croak "can't open log file: $!";
print $fh $dir;
for my $command( qq( mount '$file' /media/film), qq( cp -uvR /media/film/* $dir ),
                qq(umount /media/film  i),
                qq( chown -R fkalter:fkalter $dir/* ),
                qq( chmod -R u+rw $dir/* ),
                qq( notify-send "Iso extract done!") ){
    &back_tick_and_log($fh, $command);
}
close($fh);

sub back_tick_and_log{
    my ($fh, $command) = @_;
    my ($read, $write, $pid);
    $pid = open3($write, $read, $read, $command );
    print $fh $_ while(<$read>);
    waitpid($pid, 0);
    return;
}
