#!/home/fkalter/perl

use 5.016000;
use warnings;

use Path::Class;
use IPC::Open3 qw( open3 );
use Carp;

my ($read, $write, $pid);

chomp $ARGV[0];
my $file = file($ARGV[0]);
my $dir = $file->dir; 
$dir = quotemeta($dir);

open(my $fh, ">>", "/home/fkalter/scripts/extract-iso.log") or croak "can't open log file: $!";
print $fh $dir;

$pid = open3($write, $read, $read, qq( mount '$file' /media/film) );
print $fh $_ while(<$read>);
waitpid($pid, 0);

$pid = open3($write, $read, $read, qq( cp -vR /media/film/* $dir ));
print $fh $_ while(<$read>);
waitpid($pid, 0);

$pid = open3($write, $read, $read, qq(umount /media/film  ));
print $fh $_ while(<$read>);
waitpid($pid, 0);

$pid = open3($write, $read, $read, qq( chown -R fkalter:fkalter $dir/* ));
print $fh $_ while(<$read>);
waitpid($pid, 0);

$pid = open3($write, $read, $read, qq( chmod -R u+rw $dir/* ));
print $fh $_ while(<$read>);
waitpid($pid, 0);

close($fh);
