#!/bin/sh

find_com="find -L $1 -name '.git' -prune -o ! -name '.*' -type f \
            -exec awk '/(^#!.*perl)|(^package)/ && NR == 1 {print FILENAME; exit}' {} \;"

# get lines starting with "use", these are dependencies
filter="xargs grep -h '^use '"
 # strip the "use " part and the trailing semicolon
filter="$filter | sed -e 's/use //' -e 's/;//'"
# remove dependencies starting wat a lowercase letter or number (these are pragma's "use strict;" for example)
filter="$filter | grep -Pv '^[a-z\d]'"
# grab just the interesting bit: "use Math::Random::Secure qw( irand );"  it will grap just "Math::Random::Secure"
filter="$filter | grep -Eo '^[a-zA-Z0-9:]+'"
# call cpanm only once for every dependency found
filter="$filter | sort | uniq"

if [ -z "$1" ]; then
    echo usage: $0 perl_file_with_dependencies \[folder_to_install_dependencies\]
else
    if [ -z "$2" ]; then
        eval "$find_com | $filter | xargs cpanm"
    else
        eval "$find_com | $filter | xargs -I {} cpanm -L $2 {}"
    fi
fi
