#!/home/fkalter/perl
use v5.16;

use Linux::Inotify2;
use Path::Class;
use File::Basename;

my $not = new Linux::Inotify2 or die "unable to create new inotify object: $!";
my $path = dir("/home/fkalter/Pictures");
$not->watch( $path , IN_CREATE, \&handle );

sub handle {
    my $e = shift;
    sleep 1;
    my $file = file($path , $e->{name});
    chomp (my $res = `identify -format "\%w" $file`);
    if($res == 3840){
        `/home/fkalter/scripts/split-image $file`;
        my ( $base, $form ) = basename($file) =~ /(.+)\.(.+)/;
        my $left = file(dir( $path , "wallpapers"), "${base}-0.$form");
        my $right = file( dir( $path , "wallpapers") , "${base}-1.$form");

        `xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/image-path -s $left`;
        `xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor1/image-path -s $right`;
    }
}

1 while $not->poll;
