#!/home/fkalter/perl
use 5.016000;
use strict;
use warnings;

use IPC::Open3 qw( open3 );

my ( $read, $write, $pid );
my $sock = "/home/fkalter/vlc.sock";
if ( -e $sock && !system("echo 'logout' | nc -U $sock") ) {
    $pid = open3( $write, $read, $read, qq(echo "status" | nc -U $sock) );
    waitpid( $pid, 0 );
    if (
        do { local $/ = undef; <$read> }
        !~ /menu select/i
      )
    {
        $pid = open3( $write, $read, $read, qq(echo "pause" | nc -U $sock) );
        waitpid( $pid, 0 );
    }
}

$pid = open3( $write, $read, $read, qq(xscreensaver-command -lock) );
waitpid( $pid, 0 );
                                                  
$pid = open3( $write, $read, $read, qq(pm-suspend) );
waitpid( $pid, 0 );

