#!/home/fkalter/perl

use strict;
use warnings;
use 5.016000;
use Carp;
use File::Slurp;

my $dir = "/media/truecrypt2/down/";
my $lines = read_file( "/home/fkalter/log.txt", array_ref => 1, chomp => 1 )
  or croak "Could not open vlc-log for reading: $!";

my $file = "$dir$lines->[ scalar @$lines -1 ]";
system("trash-put \"$file\"");
system("~/scripts/vlc-random");
